import './globals.css'
import type { Metadata } from 'next'
import { Manrope } from 'next/font/google'
import { clsx } from 'clsx'

const manrope = Manrope({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={clsx(manrope.className, 'text-midnight')}>
        {children}
      </body>
    </html>
  )
}
